package de.wowlordnick2.utils.Enums;

public enum Blocking {

    AIR(),
    WALL_SIGN(),
    DEBUG_STICK(),
    BARRIER(),
    BEDROCK(),
    COMMAND_BLOCK(),
    COMMAND_BLOCK_MINECART(),
    CHAIN_COMMAND_BLOCK(),
    REPEATING_COMMAND_BLOCK(),
    STRUCTURE_BLOCK(),
    STRUCTURE_VOID(),
    DEAD_BUBBLE_CORAL_WALL_FAN(),

    //spawn eggs
    PIG_SPAWN_EGG(),
    SHEEP_SPAWN_EGG(),
    COW_SPAWN_EGG(),
    CHICKEN_SPAWN_EGG(),
    SQUID_SPAWN_EGG(),
    WOLF_SPAWN_EGG(),
    OCELOT_SPAWN_EGG(),
    HORSE_SPAWN_EGG(),
    RABBIT_SPAWN_EGG(),
    POLAR_BEAR_SPAWN_EGG(),
    LLAMA_SPAWN_EGG(),
    PARROT_SPAWN_EGG(),
    VILLAGER_SPAWN_EGG(),
    MUSHROOM_COW_SPAWN_EGG(),
    SNOWMAN_SPAWN_EGG(),

    //wall materials
    BLACK_WALL_BANNER(),
    BLUE_WALL_BANNER(),
    BROWN_WALL_BANNER(),
    CYAN_WALL_BANNER(),
    GRAY_WALL_BANNER(),
    GREEN_WALL_BANNER(),
    LIGHT_BLUE_WALL_BANNER(),
    LIGHT_GRAY_WALL_BANNER(),
    LIME_WALL_BANNER(),
    MAGENTA_WALL_BANNER(),
    ORANGE_WALL_BANNER(),
    PINK_WALL_BANNER(),
    PURPLE_WALL_BANNER(),
    RED_WALL_BANNER(),
    WHITE_WALL_BANNER(),
    YELLOW_WALL_BANNER(),
    WALL_TORCH(),

    //other things
    BUNDLE(),
    POTTED_DANDELION();

}
