name: Wowlordnick2
version: '${version}'
main: de.wowlordnick2.Main
api-version: 1.16
authors: [ Lordlorse, Ohnonick2 ]

commands:
  event:
    description: "Startet ein Event"
    aliases: [e]
    permission: "event.start"
    permission-message: "§cDu hast keine Rechte um das Event zu starten!"

  startevent:
    description: "Startet das Spiel"
    aliases: [s]
    permission: "start.start"
    permission-message: "§cDu hast keine Rechte um das Spiel zu starten!"

  timer:
    description: "Startet den Timer"
    aliases: [t]
    permission: "timer.start"
    permission-message: "§cDu hast keine Rechte um den Timer zu starten!"
  forcestart:
    description: "Startet das Spiel"
    aliases: [fs]
    permission: "forcestart.start"
    permission-message: "§cDu hast keine Rechte um das Spiel zu starten!"